mm: Fix missing prototype in try_schedule_zs_compact()
Error:
../mm/zsmalloc.c:2464:29: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
 2464 | void try_schedule_zs_compact()
      |                             ^
      |                              void
1 error generated.