fs: Fix missing prototype in sec_sys_sync()
Error:
../fs/sync.c:25:31: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   25 | static inline int sec_sys_sync() {
      |                               ^
      |                                void
1 error generated.