drivers: net: qualcomm: Fix missing prototype in rmnet_perf_free_hash_table()
Error:
../drivers/net/ethernet/qualcomm/rmnet/perf/rmnet_perf_opt.c:715:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
  715 | rmnet_perf_free_hash_table()
      |                           ^
      |                            void
1 error generated.