drivers: adsp_factory: Fix missing prototype in print_ssr_history()
Error:
../drivers/adsp_factory/ssc_core.c:653:23: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
  653 | void print_ssr_history()
      |                       ^
      |                        void
1 error generated.